version: '3.4'

services:
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  
  pbx:
    build:
      context: .
    volumes:
      - "./data/msmtprc:/etc/msmtprc"
      - "./data/asterisk:/etc/asterisk"
      - "./data/asterisk:/var/lib/asterisk"
      - "./data/asterisk-spool:/var/spool/asterisk"
      - "./data/ssl:/ssl"
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10099:10000-10099/udp"
      - "8088:8088"
      - "8089:8089"
    # networks:

volumes:
  db_data: