version: '3.4'

services:
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  
  pbx:
    image: 
      context: .
      volumes:
        - 
      ports:
        -

volumes:
  db_data: