CREATE TABLE queue (
  name varchar(128),
  musiconhold varchar(128),
  announce varchar(128),
  context varchar(128),
  timeout int8,
  monitor_join bool,
  monitor_format varchar(128),
  queue_youarenext varchar(128),
  queue_thereare varchar(128),
  queue_callswaiting varchar(128),
  queue_holdtime varchar(128),
  queue_minutes varchar(128),
  queue_seconds varchar(128),
  queue_lessthan varchar(128),
  queue_thankyou varchar(128),
  queue_reporthold varchar(128),
  announce_frequency int8,
  announce_round_seconds int8,
  announce_holdtime varchar(128),
  retry int8,
  wrapuptime int8,
  maxlen int8,
  servicelevel int8,
  strategy varchar(128),
  joinempty varchar(128),
  leavewhenempty varchar(128),
  eventmemberstatus bool,
  eventwhencalled bool,
  reportholdtime bool,
  memberdelay int8,
  weight int8,
  timeoutrestart bool,
  PRIMARY KEY (name)
) WITHOUT OIDS;
ALTER TABLE queue OWNER TO asterisk;